### ISSUE TITLE
Used MOSFET not for 3.3V logic level

### ISSUE THREAD

**Issue by lethuer** [3ative/PWM-Fan-controller#4]
I recognised the used mosfet "STP16NF06L" does not switch reliable with Uds = 12V and Ugs = 3.3V which is delivered by D1 Mini.
For 3.3V logic level a better choice could be IRLZ44N for example.

**Comment by 3ative** [comment]
Looking at the Datasheets:
The STP16NF06L has a Vgs(th) of 1V to 2.5v
The IRLZ44N  has a a Vgs(th) of 1V to 2V
So both would work.

I chose the STP16NF06L as the unit price was cheaper.

**Comment by lethuer** [comment]
From the datasheet I would agree but STP16NF06L doesn't work for me at Ugs 3.3V, with 5V the mosfet switched on.
I just tried it on the bench and wanted to point this out.

Another thread with some interesting information about logic level mosfets:
[Using MOSFETS with TTL levels (5 Volt and 3.3 Volt)](https://arduinodiy.wordpress.com/2012/05/02/using-mosfets-with-ttl-levels/)
"Another thing to beware of in datasheets is Vthresh (threshhold voltage). This is not the gate voltage to turn the device on, its the gate voltage at which it switches fully off (less than a few uA of current, typically). If Vthresh is given as 2..4V range, it cannot be a logic level MOSFET (Vthresh is usually 0.5 to 1V for logic-level MOSFETs)."

**Comment by 3ative** [comment]
Are you sure you are using the "L" or "Logic Level" version, I.E. STP16NF06**L** and not STP16NF06 ?

As stated in the link you posted:
"... logic level MOSFET (Vthresh is usually 0.5 to 1V for logic-level MOSFETs)." and the ones I spec here have a Vthresh 1V to 2.5V

**Comment by lethuer** [comment]
Yes I am...
